/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    Block: typeof import('./../components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./../components/breadcrumb/index.vue')['default']
    Chart: typeof import('./../components/chart/index.vue')['default']
    Footer: typeof import('./../components/footer/index.vue')['default']
    FormWrapper: typeof import('./../components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./../components/global-setting/index.vue')['default']
    IconAlipayCircle: typeof import('@arco-design/web-vue/es/icon')['IconAlipayCircle']
    IconApps: typeof import('@arco-design/web-vue/es/icon')['IconApps']
    IconGithub: typeof import('@arco-design/web-vue/es/icon')['IconGithub']
    IconLarkColor: typeof import('@arco-design/web-vue/es/icon')['IconLarkColor']
    IconLock: typeof import('@arco-design/web-vue/es/icon')['IconLock']
    IconSettings: typeof import('@arco-design/web-vue/es/icon')['IconSettings']
    IconTiktokColor: typeof import('@arco-design/web-vue/es/icon')['IconTiktokColor']
    IconUser: typeof import('@arco-design/web-vue/es/icon')['IconUser']
    IconWechat: typeof import('@arco-design/web-vue/es/icon')['IconWechat']
    List: typeof import('./../components/message-box/list.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    MessageBox: typeof import('./../components/message-box/index.vue')['default']
    Navbar: typeof import('./../components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/tab-bar/index.vue')['default']
    TabItem: typeof import('./../components/tab-bar/tab-item.vue')['default']
  }
}
