name: Check
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    if: github.repository == 'oljc/arco-admin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  type_check:
    if: github.repository == 'oljc/arco-admin'
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Type check
        run: pnpm run type:check
